baseURL = "https://srestack.dev/"
theme = "blowfish"
languageCode = "en"
title = "Santosh P Swamynathan"
copyright = "Â© 2025 Santosh P Swamynathan"

enableRobotsTXT = true
summaryLength = 30

[pagination]
  pagerSize = 10

[outputs]
  home = ["HTML", "RSS", "JSON"]

[taxonomies]
  tag = "tags"
  category = "categories"
  author = "authors"
  series = "series"

[module]
  [module.hugoVersion]
    extended = true
    min = "0.87.0"
