baseURL = "https://srestack.dev/"
languageCode = "en-us"
title = "Santosh Swamynathan"
theme = "blowfish"

[module]
  [module.hugoVersion]
    extended = true
    min = "0.87.0"

[taxonomies]
  category = "categories"
  tag = "tags"
  series = "series"

[menu]
  [[menu.main]]
    name = "SRE"
    pageRef = "sre"
    weight = 10
  
  [[menu.main]]
    name = "GPU Infrastructure"
    pageRef = "gpu"
    weight = 20
  
  [[menu.main]]
    name = "General"
    pageRef = "general"
    weight = 30
  
  [[menu.main]]
    name = "About"
    pageRef = "about"
    weight = 40

[params]
  description = "Senior Site Reliability Engineer @ Microsoft Azure. Large-scale GPU infrastructure and reliability engineering."
  
  colorScheme = "blowfish"
  defaultAppearance = "dark"
  autoSwitchAppearance = true
  
  enableSearch = true
  enableCodeCopy = true
  
  [params.author]
    name = "Santosh Swamynathan"
    email = "santoshswamynathan@outlook.com"
    links = [
      { github = "https://github.com/Quokkakoala" },
      { linkedin = "https://www.linkedin.com/in/santosh-swamynathan/" }
    ]
  
  [params.footer]
    showCopyright = true
    showThemeAttribution = false
    showAppearanceSwitcher = true
    showScrollToTop = true

  [params.homepage]
    layout = "profile"
    showRecent = true
    showRecentItems = 6

  [params.article]
    showDate = true
    showAuthor = true
    showBreadcrumbs = true
    showReadingTime = true
    showTableOfContents = true
    sharingLinks = ["linkedin", "twitter", "email"]

[outputs]
  home = ["HTML", "RSS", "JSON"]
