# Hugo Configuration for SRE Stack Blog
baseURL = "https://srestack.dev/"
languageCode = "en-us"
title = "Santosh Swamynathan"
theme = "blowfish"

[module]
  [module.hugoVersion]
    extended = true
    min = "0.87.0"

[taxonomies]
  category = "categories"
  tag = "tags"
  series = "series"

[menu]
  [[menu.main]]
    name = "SRE"
    pageRef = "sre"
    weight = 10
  
  [[menu.main]]
    name = "GPU Infrastructure"
    pageRef = "gpu"
    weight = 20
  
  [[menu.main]]
    name = "General"
    pageRef = "general"
    weight = 30
  
  [[menu.main]]
    name = "About"
    pageRef = "about"
    weight = 40

  [[menu.main]]
    name = "Archive"
    pageRef = "archive"
    weight = 50

[params]
  author = "Santosh Swamynathan"
  description = "Senior Site Reliability Engineer @ Microsoft Azure. Large-scale GPU infrastructure and reliability engineering."
  
  colorScheme = "blowfish"
  defaultAppearance = "dark"
  autoSwitchAppearance = true
  
  enableSearch = true
  enableCodeCopy = true
  
  [params.footer]
    showCopyright = true
    showThemeAttribution = false
    showAppearanceSwitcher = true
    showScrollToTop = true

  [params.homepage]
    layout = "profile"
    showRecent = true
    showRecentItems = 6
    showMoreLink = true
    showMoreLinkDest = "/blog"

  [params.article]
    showDate = true
    showAuthor = true
    showBreadcrumbs = true
    showDraftLabel = true
    showHeadingAnchors = true
    showPagination = true
    showReadingTime = true
    showTableOfContents = true
    showTaxonomies = true
    showComments = false
    sharingLinks = ["linkedin", "twitter", "reddit", "email"]

  [params.list]
    showBreadcrumbs = true
    showSummary = true
    showTableOfContents = false
    showCards = true
    groupByYear = true

[outputs]
  home = ["HTML", "RSS", "JSON"]
  section = ["HTML", "RSS"]
